[dependencies]
packages = [
  "mesa",
  "libglvnd",
  "libgl1",
  "libgl1-mesa-glx",
  "libglib2.0-0",
  "libsm6",
  "libxrender1",
  "libxext6",
  "python312",
  "pip"
]

[start]
cmd = "streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0"